### ISSUE TITLE
Is the surrogate check the same as what _isMaster is trying to do?

### ISSUE THREAD

**Issue by michaelherger** [philippe44/LMS-Groups#11]
https://github.com/philippe44/LMS-Groups/blob/2551b1a2e17b262c814615a9e012ddc6c4f401ca/plugin/StreamingController.pm#L78

**Comment by philippe44** [comment]
I don’t think so. The surrogate is the first device that is not the master and that is active. As the streaming controller, I receive track started event from all sync members, but of course not for the virtual player, as such events are generated by the real player using slimproto. So I need to select one player, always the same and to duplicate it’s behavior. The virtual is a shadow of this real player or the real player is a surrogate of the virtual player. So isMaster will be true for all players except the group where test with surrogate will only be true if the track start event comes from the surrogate, in which case I want to mimic it.

**Comment by philippe44** [comment]
Would you mind if I close this one?

**Comment by michaelherger** [comment]
Was wondering about this, too. Closing.
