### ISSUE TITLE
iOS 11.3 troubles?

### ISSUE THREAD

**Issue by xcracing** [philippe44/LMS-Groups#19]
I think iOS 11.3 may have broken the ability to create a group player using this plugin and airplay to it.    Was working prior to iOS 11.3

Unfortunately, I updated all my iOS devices to 11.3 before realizing this was an issue, so I can't test from 11.2

Love this plugin, hoping whatever has happened can be resolved.    My group players still work if I play directly from LMS, just not from airplay/Shairplay2 (or the fork).

**Comment by philippe44** [comment]
Just tried on my iPad with 11.3 and it still works here

**Comment by xcracing** [comment]
Well not sure what was going on.   After switching from your version of Shairtunes2 back to the original, several reboots of both LMS, Max2Play, etc, updating my PiCorePlayers - still not working, then after switching back to your fork of Shairtunes2 and executing a re-publish, they're working again.   No idea what made them quit or what made them work again.     Thanks for testing from your 11.3 device - and thanks again for this plugin, it's great!!
