### ISSUE TITLE
Player qui s'arrête si on transfert la playliste du player vers un groupe.

### ISSUE THREAD

**Issue by sifus** [philippe44/LMS-Groups#26]
Lorsque l'on fonctionne avec des groupes et que l'on souhaite passer une playliste d'un player vers un groupe (qui contient ce player), il faudrait une option qui permet de ne pas éteindre ce player.

**Comment by sifus** [comment]
Hello, avez vous pris cela en compte dans la nouvelle release ?

Merci infiniment :)

**Comment by philippe44** [comment]
Je ne comprends pas bien le cas

**Comment by sifus** [comment]
J'ai 5 players solo, et un player groupé qui les regroupent tous ("Appartement").

Si j'écoute de la musique dans ma chambre (sur "Chambre1") et que je veux transférer la musique dans tout l'appartement (sur "Appartement"), je clique sur les deux petites flèches de transfert de playliste et je sélectionne "Appartement".

La playliste passe sur le player groupé "Appartement" et donc sur tous les players qu'il contient, sauf le player "Chambre1" car il a été éteint lorsque la playliste l'a quitté.
