### ISSUE TITLE
Plugin prefs not removed when player deleted

### ISSUE THREAD

**Issue by CDrummond** [philippe44/LMS-Groups#27]
If I set a plugin preference (such as 'Dont stop the music') for a group player, this is stored in the plugin's pref file. But, when the group player is deleted these preferences are not removed.

I suggest code similar to 'Client Cleanup' is executed when a group player is deleted.

**Comment by philippe44** [comment]
I'm not sure I see the value of that. The prefs of the plugin are small no matter what, not like the server.prefs which is/was becoming huge with time.

**Comment by CDrummond** [comment]
Really? This means stale and unused config is going to remain. Why would you not want that cleaned up?

'Client Cleanup' (I think) already has the code to remove these, so (in theory) it should just be a matter of porting across.

**Comment by philippe44** [comment]
But it does not hurt anything. Having said that, I checked and the code is already there (did not remember ...). I tested it and the groups.prefs is cleaned everytime a group is removed

**Comment by CDrummond** [comment]
No, I don't mean `group.prefs` I mean the other plugin prefs files - e.g. `dontstopthemusic.prefs`

When you set a 'Dont stop the music' setting for a group (or any player) it is stored in `dontstopthemusic.prefs` It is from these files (not just `dontstopthemusic.prefs`) that the client info needs to be removed.

'Client cleanup' does remove client config from these files when it removes a client, hence thinking that Groups should do the same when they are removed.

**Comment by philippe44** [comment]
Oh, that. ok, you're a perfectionist but it's 3 lines of codes, so we have a deal :-)

Done in 0.12

**Comment by philippe44** [comment]
And thanks for the dedicated icons in material - looks really good :-)

**Comment by CDrummond** [comment]
Well, it was because of the icons that I noticed this issue. For 1.7.1 I will allow users to set an icon, and this is stored per-player in Materials config. But the item was not being removed when groups were :)

And if we're handing out thanks - a **massive** thank you to you. I really could not be using LMS so well without your AirPlay bridge. I used MPD for years, and my wife would never use it. Bought an AirPlay speaker to link to LMS, and now she finally uses our digital music collection.

**Comment by CDrummond** [comment]
Thanks for the quick fix. However, this only works when called via Group players settings page. A similar change needs to be implemented in the JSONRPC API. Patch is:

```
--- Plugin.pm.orig	2020-05-25 13:57:25.674140941 +0100
+++ Plugin.pm	2020-05-25 13:57:45.332205510 +0100
@@ -524,6 +524,9 @@
 		}
 		main::INFOLOG && $log->is_info && $log->info("Deleting $id");
 		$prefs->remove($Slim::Utils::Prefs::Client::clientPreferenceTag . ':' . $id);
+		foreach my $namespace (@{ Slim::Utils::Prefs::namespaces() }) {
+			preferences($namespace)->remove($Slim::Utils::Prefs::Client::clientPreferenceTag . ':' . $id);
+		}
 		delPlayer($id);
 		$request->setStatusDone();
 		return;
```

**Comment by philippe44** [comment]
argh ... was definitively too late to make even the slightest modification :-)
