### ISSUE TITLE
List members in server status message

### ISSUE THREAD

**Issue by CDrummond** [philippe44/LMS-Groups#28]
I'm 99.99% sure this wont be possible, but... Any chance that a group player could list its current group members in the response to a status message? This would be when the group is **not** active.

I'm thinking not, as this status message would be created by LMS, but perhaps its possible?

The reason I ask is that I'd like to list the current group members  in Material's 'Manage players' dialog. Then I could allow dragging players out of a group, etc. I know I could poll the list of members, but it'd be nicer if it was in the status message.

**Comment by philippe44** [comment]
It's possible to set a hook on "status" query, I've already done that for my UPnP & CC plugins. I pushed a proposal (you need to look on GitHub, I've not package the files, but it's just one file and I don't think it's going to be a problem for you :-)

**Comment by CDrummond** [comment]
Works perfectly, thanks!
