### ISSUE TITLE
LMS crashing (out of memory) with plugin "Group Players" activated

### ISSUE THREAD

**Issue by schnillerman** [philippe44/LMS-Groups#30]
Hi,

since update to squeezeserver version 8.1.2-1610697261, with the **_Group Players_** plugin installed, the server crashes / does not respond anymore. It runs out of memory (uses 11G+ on 12G linux box).

Deleting the directory of the *_Group Players_* plugin (location: `/var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/`_**Groups**_) solves the issue.

`systemctl restart logitechmediaserver.service` afterwards works fine and occupies about 350-400MB of memory as usual.

**Comment by schnillerman** [comment]
https://github.com/Logitech/slimserver/issues/513#issue-787708165

**Comment by philippe44** [comment]
Set the debug level of the Group plugin to at least info (debug preferred) and send some server.log. There is nothing I can do w/o a log

**Comment by schnillerman** [comment]
Thanks a bunch for the reply! Okay will do. Am fairly good with the CLI but need info on how to turn on debug for the plugin.
Also, I will not be able to complete startup of the LMS and therefore need to stop it at some point via systemctl stop. I hope this still yields the info you need in the server.log.

Regards, Till

**Comment by philippe44** [comment]
You need to use the WebUI

**Comment by schnillerman** [comment]
But how? If plugin is activated, I can't reach the webui. The server just starts, uses up all of the ram and isn't reachable.

**Comment by mherger** [comment]
When LMS is down, go to its prefs folder. There you'd find log.conf. Open it in your text editor of choice, find the entry for `plugin.group` and replace `ERROR` with `DEBUG`. Start LMS.

**Comment by schnillerman** [comment]
OK, server log is attached with plugin.groups logging set to debug as per @mherger's comment above.

Ever since I switched plugin.groups = ERROR to DEBUG, the server starts fine, but it keeps rescanning my library.
```
root@LMS:~# systemctl status logitechmediaserver.service
● logitechmediaserver.service - LSB: Startup script for the Logitech Media Server
   Loaded: loaded (/etc/init.d/logitechmediaserver; generated; vendor preset: enabled)
   Active: active (running) since Mon 2021-01-18 16:17:58 CET; 9s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1334 ExecStop=/etc/init.d/logitechmediaserver stop (code=exited, status=0/SUCCESS)
  Process: 1344 ExecStart=/etc/init.d/logitechmediaserver start (code=exited, status=0/SUCCESS)
    Tasks: 3 (limit: 4915)
   Memory: 659.7M
      CPU: 11.097s
   CGroup: /system.slice/logitechmediaserver.service
           ├─1350 /bin/bash /usr/sbin/squeezeboxserver_safe /usr/sbin/squeezeboxserver --prefsdir /var/lib/squeezeboxserver/prefs --logdir /var/log/squeezeboxse
           ├─1352 /usr/bin/perl /usr/sbin/squeezeboxserver --prefsdir /var/lib/squeezeboxserver/prefs --logdir /var/log/squeezeboxserver/ --cachedir /var/lib/sq
           └─1356 /usr/bin/perl /usr/sbin/squeezeboxserver-scanner --noimage --prefsdir=/var/lib/squeezeboxserver/prefs --rescan --novideo --priority=0 --logcon

Jan 18 16:17:58 LMS systemd[1]: Starting LSB: Startup script for the Logitech Media Server...
Jan 18 16:17:58 LMS logitechmediaserver[1344]: Making sure that Logitech Media Server is not running first: start-stop-daemon: warning: failed to kill 1231: No
Jan 18 16:17:58 LMS logitechmediaserver[1344]: No process in pidfile '/var/run/logitechmediaserver.pid' found running; none killed.
Jan 18 16:17:58 LMS logitechmediaserver[1344]: Starting Logitech Media Server.
Jan 18 16:17:58 LMS systemd[1]: Started LSB: Startup script for the Logitech Media Server.

```

[server.log.zip](https://github.com/philippe44/LMS-Groups/files/5830901/server.log.zip)

**Comment by philippe44** [comment]
I don't see anything specific in that log. Maybe erase the unconnected client with Michael's client cleanup plugin and then stop LMS then delete the file /var/lib/squeezeboxserver/prefs/plugin/groups.pref and see if it still happens.
