### ISSUE TITLE
Are members supposed to play synchronised

### ISSUE THREAD

**Issue by howff** [philippe44/LMS-Groups#31]
Are all the members of a Group supposed to play completely synchronised?

I've got a Chromecast Audio and an AudioCast (because you can't buy Chromecast Audio any more) in a group but the sync is off right from the start, and I think it's even getting worse during the playlist.

**Comment by philippe44** [comment]
Yes, that's the very purpose of the plugin, to assemble groups on the fly (dynamic groups). But if you read the doc of my ChromecCast plugin (which is what I assume you use), it clearly says that CC devices *cannot* be synchronized by LMS (unless they are part of an internal, ChromeCast group, made by Google controller, not by LMS).

**Comment by howff** [comment]
Ah, thank you.
