### ISSUE TITLE
Group Players makes all my other players, except Touch and Group-player to disappear

### ISSUE THREAD

**Issue by jasell** [philippe44/LMS-Groups#34]
For some reason Group Player can make all your players disappear.

If disabling Group player plugin and restarting, then all players are back.
Or if enabling Group Player and deleting the preference file, and restarting, then all players comes back.

At some point Group Player make the preferences incompatible/corrupt.
Would be great if you could make a check preventing this from happening, i.e. automatically clear out bad-settings.

**Comment by JockeJarre** [comment]
I see the same, when I reboot LMS with the group player active I can not see any of the hardware players. (2 squeezeboxes)
I then noticed that when I want to access the group player configuration, that it does not want to show.
When I then uninstall the group player, LMS finds the hardware players again.

I am using the LMS Version: 8.5.3

**Comment by jasell** [comment]
> I see the same, when I reboot LMS with the group player active I can not see any of the hardware players. (2 squeezeboxes) I then noticed that when I want to access the group player configuration, that it does not want to show. When I then uninstall the group player, LMS finds the hardware players again.
> 
> I am using the LMS Version: 8.5.3

My solution was to delete the GroupPlayer settings file.

**Comment by jasell** [comment]
Closing this issue as it is resolved

**Comment by JockeJarre** [comment]
> > I see the same, when I reboot LMS with the group player active I can not see any of the hardware players. (2 squeezeboxes) I then noticed that when I want to access the group player configuration, that it does not want to show. When I then uninstall the group player, LMS finds the hardware players again.
> > I am using the LMS Version: 8.5.3
> 
> My solution was to delete the GroupPlayer settings file.

Hej,  
I tried the same today, deleting /var/lib/squeezeboxserver/prefs/plugin/groups.prefs:

At first it looked fine, but now I restarted the server and the hardware players are gone again. 

Did you delete any other file(s)?
